version: '3.1'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - "5532:5432"
  redis:
    image: redis:4.0.10-alpine
    ports:
      - '6379:6379'
